### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/practica-de-hilos-uzias10#2]
[Practica Hilos C#.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-uzias10/files/6512172/Practica.Hilos.C.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 19.4/20

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 19.4/20

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by josealfredo79** [comment]
Bien hecho y revisado
